name: Publish Python Package to PyPI

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout script repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload -u $username -p $password  dist/*
        
